name: Code Linting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t code-linter .

      - name: Run Python Linting
        run: |
          docker run --rm -v "$(pwd)":/app code-linter pylint /app

      - name: Run Java Linting
        run: |
          docker run --rm -v "$(pwd)":/app code-linter java -jar checkstyle.jar -c google_checks.xml /app
