name: Code Linting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Download Checkstyle
        run: |
          wget -q -O checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.21.1/checkstyle-10.21.1-all.jar

      - name: Build Docker image
        run: |
          docker build -t code-linter .

      - name: Run Python Linting
        run: |
          docker run --rm -v "$(pwd)":/app code-linter pylint /app

      - name: Run Java Linting
        run: |
          docker run --rm -v "$(pwd)":/app code-linter java -jar /app/checkstyle.jar -c /app/google_checks.xml /app
          
      - name: Run Checkstyle
        run: java -jar checkstyle.jar -c google_checks.xml sample.java
        continue-on-error: true
